### ISSUE TITLE
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

### ISSUE THREAD

**Issue by ethicalhack3r** [huwwp/cryptop#10]
Installed with ```sudo pip install cryptop``` on macOS 10.12.5

Then, when I run ```cryptop```:

```
$ cryptop
Traceback (most recent call last):
  File "/Users/ryan/.rvm/bin/cryptop", line 11, in <module>
    load_entry_point('cryptop==0.1.2', 'console_scripts', 'cryptop')()
  File "/Users/ryan/.rvm/lib/python2.7/site-packages/cryptop.py", line 201, in main
    os.makedirs(basedir, exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
```

Do you know how I might solve this issue? Thanks!

**Comment by huwwp** [comment]
Requires python3, I've only tested in 3.6 so far

**Comment by ethicalhack3r** [comment]
Bah, I did read the readme but missed that part. I'll install Python3, thanks for the help!
