### ISSUE TITLE
Cannot run 0.1.2

### ISSUE THREAD

**Issue by tobias-kuendig** [huwwp/cryptop#15]
After upgrading from 0.1.1 to 0.1.2 I get to following error during startup:

```
Traceback (most recent call last):
  File "/usr/local/bin/cryptop", line 9, in <module>
    load_entry_point('cryptop==0.1.2', 'console_scripts', 'cryptop')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/cryptop-0.1.2-py2.7.egg/cryptop.py", line 6, in <module>
    import configparser
ImportError: No module named configparser
```

**Comment by tobias-kuendig** [comment]
Nevermind. I was running python2.7.
