### ISSUE TITLE
Having troubles with installation via sudo python setup.py install (see logs)

### ISSUE THREAD

**Issue by veonindustries** [huwwp/cryptop#25]
```
vitticus@kali:~/cryptop-master$ ls
config.ini  img          MANIFEST.in  requirements.txt  todo.txt
cryptop.py  LICENSE.txt  README.rst   setup.py
vitticus@kali:~/cryptop-master$ python --version
Python 3.6.2
vitticus@kali:~/cryptop-master$ sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'
vitticus@kali:~/cryptop-master$ 


```

**Comment by christian-fei** [comment]
I'm having this issue:

after a install via `sudo pip install cryptop`

```
Traceback (most recent call last):
  File "/usr/local/bin/cryptop", line 11, in <module>
    load_entry_point('cryptop==0.1.2', 'console_scripts', 'cryptop')()
  File "/usr/local/lib/python3.6/site-packages/cryptop.py", line 204, in main
    config = read_configuration(conffile)
  File "/usr/local/lib/python3.6/site-packages/cryptop.py", line 24, in read_configuration
    shutil.copyfile(defaultconf, conffile)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/site-packages/config.ini'
```

**Comment by christian-fei** [comment]
I will try to update python to 3.6 or higher tomorrow and report back.

**Comment by huwwp** [comment]
Hi Veon, looks like Kali/your python install doesn't include setuptools, I'll make it clear that it is a requirement. You can install it with `apt-get install python3-setuptools`

**Comment by huwwp** [comment]
Christian did it create the .cryptop folder in your home directory and the ini inside it?

**Comment by huwwp** [comment]
Hi Christian, I patched it, should be working now

**Comment by christian-fei** [comment]
works, thanks a lot :)
