### ISSUE TITLE
Crashing at startup

### ISSUE THREAD

**Issue by camalolo** [huwwp/cryptop#28]
Installed with :
sudo pip install cryptop

When running :
$ cryptop
Traceback (most recent call last):
  File "/usr/local/bin/cryptop", line 9, in <module>
    load_entry_point('cryptop==0.1.5', 'console_scripts', 'cryptop')()
  File "/usr/local/lib/python2.7/dist-packages/cryptop/cryptop.py", line 214, in main
    os.makedirs(BASEDIR, exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

**Comment by camalolo** [comment]
Ah sorry I am using Python 2.7. Will try with Python 3+
