### ISSUE TITLE
After entering symbol amount eg. ETH,10 I got this error message. Any idea how to fix? 

### ISSUE THREAD

**Issue by veonindustries** [huwwp/cryptop#3]
Traceback (most recent call last):
  File "/usr/local/bin/cryptop", line 9, in <module>
    load_entry_point('cryptop==0.1.0', 'console_scripts', 'cryptop')()
  File "/usr/local/lib/python2.7/dist-packages/cryptop-0.1.0-py2.7.egg/cryptop.py", line 237, in main
    wrapper(mainc)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/cryptop-0.1.0-py2.7.egg/cryptop.py", line 226, in mainc
    coinl, heldl = add_coin(data, coinl, heldl)
  File "/usr/local/lib/python2.7/dist-packages/cryptop-0.1.0-py2.7.egg/cryptop.py", line 181, in add_coin
    if if_coin(input[0]):
  File "/usr/local/lib/python2.7/dist-packages/cryptop-0.1.0-py2.7.egg/cryptop.py", line 16, in if_coin
    data = t.json()
TypeError: 'dict' object is not callable

**Comment by huwwp** [comment]
Needs python 3, sorry I'll update the readme to make that clear

**Comment by huwwp** [comment]
I updated the readme to let people know
