### ISSUE TITLE
Lunyr LUN not working

### ISSUE THREAD

**Issue by CreseQ** [huwwp/cryptop#56]
Adding Lunyr to the portfolio lead to a crash of cryptop. 

`Traceback (most recent call last):
  File "/home/user1/anaconda3/bin/cryptop", line 11, in <module>
    load_entry_point('cryptop==0.2.0', 'console_scripts', 'cryptop')()
  File "/home/user1/anaconda3/lib/python3.6/site-packages/cryptop/cryptop.py", line 269, in main
    curses.wrapper(mainc)
  File "/home/user1/anaconda3/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/user1/anaconda3/lib/python3.6/site-packages/cryptop/cryptop.py", line 223, in mainc
    write_scr(stdscr, wallet, y, x)
  File "/home/user1/anaconda3/lib/python3.6/site-packages/cryptop/cryptop.py", line 142, in write_scr
    str_formatter(coin, val, held), x, curses.color_pair(2))
  File "/home/user1/anaconda3/lib/python3.6/site-packages/cryptop/cryptop.py", line 108, in str_formatter
    val_str = '{:>{},.{}f}'.format(float(held) * val[0], max_length, dec_place)
TypeError: can't multiply sequence by non-int of type 'float'
`

Thanks a lot for this little app, very simple but powerful ;)

**Comment by CreseQ** [comment]
Same issue as https://github.com/huwwp/cryptop/issues/54
sorry for disturbing
