### ISSUE TITLE
TypeError: can't multiply sequence by non-int of type 'float' - BNB and ICX coin triggers error

### ISSUE THREAD

**Issue by derhornspieler** [huwwp/cryptop#57]
> Traceback (most recent call last):
  File "/usr/local/bin/cryptop", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/cryptop/cryptop.py", line 270, in main
    curses.wrapper(mainc)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/cryptop/cryptop.py", line 224, in mainc
    write_scr(stdscr, wallet, y, x)
  File "/usr/local/lib/python3.6/site-packages/cryptop/cryptop.py", line 142, in write_scr
    str_formatter(coin, val, held), x, curses.color_pair(2))
  File "/usr/local/lib/python3.6/site-packages/cryptop/cryptop.py", line 108, in str_formatter
    val_str = '{:>{},.{}f}'.format(float(held) * val[0], max_length, dec_place)
TypeError: can't multiply sequence by non-int of type 'float'

**Comment by GalEldarDev** [comment]
Duplicate of #54
